name: Release

concurrency:
  group: ${{ github.workflow }}

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  lint_and_test:
    name: Lint and test
    uses: ./.github/workflows/lint-and-test.yml

  release:
    name: Release
    runs-on: ubuntu-latest
    needs:
      - lint_and_test
    steps:
      - name: Git clone repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up environment
        uses: ./.github/actions/prepare-environment

      - name: Configure Git user
        run: |
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config user.name "github-actions[bot]"
          git config push.autoSetupRemote true

      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npm run release
